# Generated by Django 4.2.2 on 2023-07-07 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='nombre',
            new_name='nombre_wishlist',
        ),
    ]
