# Generated by Django 4.2.2 on 2023-07-03 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detalle',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productowishlist',
            unique_together=set(),
        ),
    ]
