# Generated by Django 4.2.2 on 2023-07-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_rename_nombre_wishlist_nombre_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estadopedido',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En preparacion', 'En preparación'), ('Entregado', 'Entregado'), ('En Despacho', 'En Despacho'), ('Cancelado', 'Cancelado')], max_length=50),
        ),
    ]
