# Generated by Django 4.2.2 on 2023-07-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_cliente_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion_despacho',
            field=models.CharField(max_length=100),
        ),
    ]
